# Generated by Django 3.2.25 on 2024-04-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
